### ISSUE TITLE
Dropdown style list

### ISSUE THREAD

**Issue by Korb** [winghongchan/dark-docs#6]
![Screenshot_20220508_171509](https://user-images.githubusercontent.com/3509797/167300417-72ae1311-b4d5-4ce2-b9b8-51f2456f183f.png)
Mozilla Firefox 100.0 (64-bit), Stylus 1.5.21 (30 August 2021)

**Comment by winghongchan** [comment]
I’ve never seen that menu looking like that…

One issue that I’ve seen before was that the styles were illegible because they were shown as black on dark gray. That has since been fixed, and I might have fixed the issue you are experiencing too. Please let me know if the issue is fixed when you get the chance. 

![image](https://user-images.githubusercontent.com/64437199/180588814-c3bd64c0-1e8a-4f96-85f6-8ed2c712e02a.png)

P.S. If you actually want to make your text look like that, look for “Redacted” in the More fonts window of Google Docs. The two fonts are great for replacing lorem ipsum if you find actual lorem ipsum distracting. Just be warned to not use Redacted Script for redacting information, as there are [scripts to un-redact](https://github.com/christiannaths/redacted-font/issues/27) Redacted Script.

**Comment by Korb** [comment]
> Please let me know if the issue is fixed when you get the chance.

Dark Docs 20220426.23.11, Stylus 1.5.25 (11 June 2022), Mozilla Firefox 103.0 (64-bit), Microsoft Windows 10.0.19043.1826 — the error I described, alas, is still present.

> look for “Redacted” in the More fonts window of Google Docs

There doesn't seem to be any:

![Google Docs — Fonts](https://user-images.githubusercontent.com/3509797/180599657-cdf9c9a8-c004-41c8-8b44-3cd3a48b5447.png)

**Comment by Korb** [comment]
![2022-10-13_15-23-00](https://user-images.githubusercontent.com/3509797/195595007-56d624de-4936-4a9f-b5cc-56a2cdd2679d.png)

Now everything is OK. I don't know what exactly was the problem.

Dark Docs 2022.8.12, Mozilla Firefox 105.0.3 (64-bit), Microsoft Windows 10.0.19044.2130.
